# Generated by Django 2.0 on 2018-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180113_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='user', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='period',
            field=models.CharField(blank=True, choices=[('3', '3기'), ('4', '4기'), ('5', '5기'), ('6', '6기'), ('7', '7기')], max_length=2, verbose_name='기수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('instructor', '강사'), ('assistant', '조교'), ('manager', '매니저'), ('student', '수강생')], max_length=20, verbose_name='사용자 타입'),
        ),
    ]
